# Generated by Django 6.0.3 on 2026-03-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_por_noche', models.IntegerField()),
                ('capacidad_personas', models.IntegerField()),
                ('cantidad_habitaciones', models.IntegerField(default=1)),
                ('cantidad_banos', models.IntegerField(default=1)),
                ('tiene_cocina', models.BooleanField(default=True)),
                ('tiene_wifi', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cabanas/')),
            ],
        ),
    ]
