# Generated by Django 6.0.3 on 2026-03-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria_cabanas/')),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='reservas.cabana')),
            ],
        ),
    ]
