# Generated by Django 6.0.3 on 2026-03-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_imagencabana'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabana',
            name='acepta_mascotas',
            field=models.BooleanField(default=False, verbose_name='¿Acepta Mascotas (Pet Friendly)?'),
        ),
        migrations.AddField(
            model_name='cabana',
            name='tiene_aire_acondicionado',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Aire Acondicionado/Calefacción?'),
        ),
        migrations.AddField(
            model_name='cabana',
            name='tiene_estacionamiento',
            field=models.BooleanField(default=False, verbose_name='¿Estacionamiento Privado?'),
        ),
        migrations.AddField(
            model_name='cabana',
            name='tiene_parrilla',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Zona de Parrilla/Asados?'),
        ),
        migrations.AddField(
            model_name='cabana',
            name='tiene_tv',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Televisión?'),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='cantidad_banos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='cantidad_habitaciones',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='precio_por_noche',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='tiene_cocina',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cabana',
            name='tiene_wifi',
            field=models.BooleanField(default=False),
        ),
    ]
