# Generated by Django 6.0.3 on 2026-03-21 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_cabana_acepta_mascotas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_huesped', models.CharField(max_length=100, verbose_name='Nombre del Huésped')),
                ('email_huesped', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono_huesped', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('fecha_llegada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cantidad_personas', models.IntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente (Por pagar/confirmar)'), ('confirmada', 'Confirmada y Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.cabana')),
            ],
        ),
    ]
