# Generated by Django 6.0.3 on 2026-03-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.IntegerField(),
        ),
    ]
