# Generated by Django 6.0.3 on 2026-03-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reserva_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabana',
            name='precio_por_noche',
            field=models.IntegerField(),
        ),
    ]
